!!ru.project.game.settings.Settings
cols: 60
delay: 100
firstGeneration:
  cellAmount: -1
  coordinates:
  - col: 0
    row: 2
  - col: 1
    row: 2
  - col: 2
    row: 2
  - col: 2
    row: 1
  - col: 1
    row: 0
  random: false
rows: 30
